services:
  - docker
language: node_js
node_js:
  - '8'
before_install:
  - docker run -d --rm -it -p "8087:8087" antidotedb/antidote
  - sudo apt-get -qq update
  - sudo apt-get install -y libfuse-dev fuse

